### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by whitesnow9291** [OneBusAway/onebusaway-gtfs-modules#104]
When I run the cmd `java -jar onebusaway-gtfs-merge-cli-1.3.3.jar`
I got this error
`no main manifest attribute, in onebusaway-gtfs-merge-cli-1.3.3.jar`

**Comment by sheldonabrown** [comment]
You need the jar with dependencies:
http://nexus.onebusaway.org/nexus/content/groups/public/org/onebusaway/onebusaway-gtfs-merge-cli/1.3.3/onebusaway-gtfs-merge-cli-1.3.3-jar-with-dependencies.jar

**Comment by whitesnow9291** [comment]
Thank!
