### ISSUE TITLE
Should OneBusAway repo use https?

### ISSUE THREAD

**Issue by gmellemstrand** [OneBusAway/onebusaway-gtfs-modules#116]
OpenTripPlanner uses OneBusAway as a dependency. This is the only repository left that does not use https. Is it possible to change this to https? I see that https://onebusaway.org/ uses https.

`<repositories>
	<repository>
		<id>public.onebusaway.org</id>
		<url>http://nexus.onebusaway.org/content/groups/public/</url>
	</repository>
</repositories>`

**Comment by hbruch** [comment]
I agree wit @gmellemstrand that OneBusAway should switch to https to provide better security. This [sonatype blog article](https://blog.sonatype.com/central-repository-moving-to-https) provides a good overview about the backgrounds.

**Comment by sheldonabrown** [comment]
Fixed

https://repo.camsys-apps.com/releases/

See POM

**Comment by hbruch** [comment]
@sheldonabrown Thanks for the info. Would you mind updating the README.md which still refers to the old one. Thanks.

**Comment by sheldonabrown** [comment]
Done
