### ISSUE TITLE
Release documentation is broken after v1.3.4

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-gtfs-modules#144]
**Summary:** 

If you look at the release notes for this repo:
http://developer.onebusaway.org/modules/onebusaway-gtfs-modules/current/release-notes.html

...the last version shown is v1.3.4.

However, releases as far as 1.3.87 appear on GitHub:
https://github.com/OneBusAway/onebusaway-gtfs-modules/releases

**Steps to reproduce:** 

Compare release notes docs to GitHub releases

**Expected behavior:** 

They should match in terms of most recent version

**Observed behavior:** 

Release notes stopped being published as of v1.3.4

**Comment by hbruch** [comment]
@sheldonabrown Any chance that this might be fixed? Is there anything this bug depends on, we could help to solve?

**Comment by sheldonabrown** [comment]
I have the javadoc building again.

I've updated the snapshot, I'll see if we can add a summary before the next release.  See:

http://developer.onebusaway.org/modules/onebusaway-gtfs-modules/current-SNAPSHOT/release-notes.html
