### ISSUE TITLE
Fares V2 attributes

### ISSUE THREAD

**Issue by leonardehrenfried** [OneBusAway/onebusaway-gtfs-modules#194]
Fares V2 has been recently added to the mainline GTFS spec.

I'm planning to add support for those new files and properties to this library, so this issue is for tracking the progress.

In a first PR I will focus on the features already in the main spec but I'm planning on also contributing things that are more speculative.

**Comment by sheldonabrown** [comment]
Thanks!  I see lots of activity still -- should this be considered ready or should I wait a little longer?

Sheldon

**Comment by leonardehrenfried** [comment]
I thought it was ready to merge but after doing the actual import into OTP I noticed a few more problems. Maybe hold off reviewinf for a few more days. 

If you already notice something that looks odd, you can already tell me and I will fix it.

**Comment by leonardehrenfried** [comment]
One question: I would like to also add files and columns that aren't part of the spec yet. Would you like all of them in a single request or separate ones?

**Comment by sheldonabrown** [comment]
Sorry, I missed the question.  A single request is fine, no need to split it out.

**Comment by leonardehrenfried** [comment]
Ok, then the PR is ready to review: https://github.com/OneBusAway/onebusaway-gtfs-modules/pull/197

**Comment by leonardehrenfried** [comment]
This has been implemented for a while.
