### ISSUE TITLE
Download links at https://developer.onebusaway.org/modules/onebusaway-gtfs-modules/current/ not working

### ISSUE THREAD

**Issue by Ge-Rag** [OneBusAway/onebusaway-gtfs-modules#276]
I cannot download from any of the links on this page.

For example: 
https://repo.camsys-apps.com/snapshots/org/onebusaway/onebusaway-gtfs-merge-cli/1.4.16-SNAPSHOT/onebusaway-gtfs-merge-cli-1.4.16-SNAPSHOT.jar

I get this in my browser:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
snapshots/org/onebusaway/onebusaway-gtfs-merge-cli/1.4.16-SNAPSHOT/onebusaway-gtfs-merge-cli-1.4.16-SNAPSHOT.jar
</Key>
<RequestId>R41BHSESAJXYF17Q</RequestId>
<HostId>
2Gf6zeaJx8+mKEiPBtPHiuaA91aohhh23rcXVEVxqj7pZn2Hbz/9v3QJ128HJpGplGBCQHgKFzA=
</HostId>
</Error>
```

Can you please correct this.

Thanks,

George

**Comment by leonardehrenfried** [comment]
Hello, I'm the new maintainer of this library and all artifacts are now deployed to Maven Central.

If you're interested in contributing some documentation (check the docs folder) I can tell you the exact download location.

**Comment by Ge-Rag** [comment]
> Hello, I'm the new maintainer of this library and all artifacts are now deployed to Maven Central.
> 
> If you're interested in contributing some documentation (check the docs folder) I can tell you the exact download location.

I don't get it. I just wanted to download the most up to date jar files, such as the gtfs-merge-cli.jar. Where can I find working download links?

**Comment by leonardehrenfried** [comment]
Open Source needs contributors so I'm looking for people who can help me improve the documentation. Are you interested?

**Comment by Ge-Rag** [comment]
Thanks a lot Aaron!

Kind regards,

Georg Ragaz
https://trainspotter.ragaz.net<https://trainspotter.ragaz.net/>

Von: Aaron Brethorst ***@***.***>
Gesendet: Mittwoch, 4. September 2024 18:30
An: OneBusAway/onebusaway-gtfs-modules ***@***.***>
Cc: Ge-Rag ***@***.***>; Mention ***@***.***>
Betreff: Re: [OneBusAway/onebusaway-gtfs-modules] Download links at https://developer.onebusaway.org/modules/onebusaway-gtfs-modules/current/ not working (Issue #276)


@Ge-Rag<https://github.com/Ge-Rag> you can find all of our published artifacts at https://repo1.maven.org/maven2/org/onebusaway/

-

**Comment by leonardehrenfried** [comment]
It's now also part of the documentation.
