### ISSUE TITLE
Where is onebusaway-gtfs-transformer-cli-1.3.4-SNAPSHOT.jar file?

### ISSUE THREAD

**Issue by aborruso** [OneBusAway/onebusaway-gtfs-modules#44]
Hi all,
I would like to download it, but the url here http://developer.onebusaway.org/modules/onebusaway-gtfs-modules/1.3.4-SNAPSHOT/onebusaway-gtfs-transformer-cli.html does not work.

Thank you

**Comment by barbeau** [comment]
I'm closing this, as the URL http://developer.onebusaway.org/modules/onebusaway-gtfs-modules/1.3.4-SNAPSHOT/onebusaway-gtfs-transformer-cli.html now appears to work, as does the direct download of the JAR file http://nexus.onebusaway.org/service/local/artifact/maven/content?r=public&g=org.onebusaway&a=onebusaway-gtfs-transformer-cli&v=1.3.4-SNAPSHOT.

This was like opened when we were having some Maven repo issues that should be resolved now.

If you still have problems please let me know.

**Comment by aborruso** [comment]
Thank you @barbeau
