### ISSUE TITLE
Cannot set timepoint flag to approximate (0)

### ISSUE THREAD

**Issue by mattwigway** [OneBusAway/onebusaway-gtfs-modules#46]
In StopTime, it is not possible to set the timepoint flag for a stop time to 0 (approximate). If you call StopTime.setTimepoint(0), and then export the feed, 0 is seen as the default value for that field and the field is left empty. But zero [does not mean the same as an empty field](https://developers.google.com/transit/gtfs/reference#stop_times_fields):

    empty - Times are considered exact.
    0 - Times are considered approximate.
    1 - Times are considered exact.

**Comment by bdferris** [comment]
I've updated the module to better support timepoint semantics.  Do you want to try a SNAPSHOT build of onebusaway-gtfs to verify the behavior matches what you expect?
