### ISSUE TITLE
Non existing 1.3.6 version for onebusaway-csv-entities?

### ISSUE THREAD

**Issue by russellhoff** [OneBusAway/onebusaway-gtfs-modules#67]
I just added the following dependency to my pom.xml file:

> 		<dependency>
			<groupId>com.github.OneBusAway</groupId>
			<artifactId>onebusaway-gtfs-modules</artifactId>
			<version>onebusaway-gtfs-modules-1.3.6</version>
		</dependency>

But Eclipse tells me the following:

Java Build Path Problems (1 item)
The container 'Maven Dependencies' references non existing library 'C:\Users\Jon Inazio\.m2\repository\org\onebusaway\onebusaway-csv-entities\1.3.6\onebusaway-csv-entities-1.3.6.jar'

Java Problems
The project cannot be built until build path errprs are resolved

Maven Dependency Problem (2 items)
Missing artifact org.onebusaway:onebusaway-collections:jar:1.3.6
Missing artifact org.onebusaway:onebusaway-csv-entities:1.3.6

What can I do?

**Comment by barbeau** [comment]
@russellhoff Did you add the OBA Maven repo to your `pom.xml`?

~~~
  <repositories>
    <repository>
      <id>public.onebusaway.org</id>
      <url>http://nexus.onebusaway.org/content/groups/public/</url>
    </repository>
  </repositories>
~~~

**Comment by russellhoff** [comment]
@barbeau Yes I've added it. I'm not at work and I don't have the code right now, so on monday I'll post it... But anyway, I don't know why is that happening. Thanks!

**Comment by barbeau** [comment]
Oh, looking at your XML more closely, you have the wrong group and version - it should be:

~~~
      <groupId>org.onebusaway</groupId>
      <artifactId>onebusaway-csv-entities</artifactId>
      <version>1.3.6</version>
~~~

**Comment by russellhoff** [comment]
I've those repositories configured in my pom.xml file:

> 
	<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
		<repository>
			<id>public.onebusaway.org</id>
			<url>http://nexus.onebusaway.org/content/groups/public/</url>
	    </repository>
	</repositories>

**Comment by russellhoff** [comment]
Just added this dependency and I get no errors:

> 
		<dependency>
			<groupId>com.github.OneBusAway.onebusaway-gtfs-modules</groupId>
			<artifactId>onebusaway-gtfs</artifactId>
			<version>onebusaway-gtfs-modules-1.3.6</version>
		</dependency>

Why? Besides, in Maven Repository the latest version seems to be 1.3.4, instead of 1.3.6.

**Comment by barbeau** [comment]
@russellhoff Sorry, XML to include gtfs modules should have been:

~~~
<dependency>
  <groupId>org.onebusaway</groupId>
      <artifactId>onebusaway-gtfs-modules</artifactId>
      <version>1.3.6</version>
</dependency>
~~~

If that doesn't work, you can always clone the gtfs-modules project locally:
https://github.com/OneBusAway/onebusaway-gtfs-modules

...checkout the 1.3.6 tag:

`git checkout tags/onebusaway-gtfs-modules-1.3.6`

...and then install it to your local maven repo:

`mvn install -DskipTests`

**Comment by russellhoff** [comment]
Thanks for your suggestions @barbeau . Jitpack is a plugin that does github importation onto maven automatically, that is why I typed weird stuff in the dependency. Anyway, I don't know why it isn't updated the libraries in maven repository...

**Comment by russellhoff** [comment]
@barbeau If I add the dependency you commented me, I get this message:

> Missing artifact org.onebusaway:onebusaway-gtfs-modules:jar:1.3.6

**Comment by barbeau** [comment]
@russellhoff Ok - did you try the workaround to clone and install the https://github.com/OneBusAway/onebusaway-gtfs-modules yourself?

@sheldonabrown Could you check to make sure `onebusaway-gtfs-modules` v `1.3.6` got deployed to the OBA Maven repo?  It does look like it's missing - I just tried to include it in a project and got the following:

~~~
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building OneBusAway Client Library 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://nexus.onebusaway.org/content/groups/public/org/onebusaway/on
ebusaway-gtfs-modules/1.3.6/onebusaway-gtfs-modules-1.3.6.pom
Apr 27, 2016 9:28:39 AM org.apache.maven.wagon.providers.http.httpclient.client.
protocol.ResponseProcessCookies processCookies
WARNING: Cookie rejected: "[version: 0][name: rememberMe][value: deleteMe][domai
n: nexus.onebusaway.org][path: /nexus][expiry: Wed Apr 27 09:28:39 EDT 2016]". I
llegal path attribute "/nexus". Path of origin: "/content/groups/public/org/oneb
usaway/onebusaway-gtfs-modules/1.3.6/onebusaway-gtfs-modules-1.3.6.pom"
Apr 27, 2016 9:28:39 AM org.apache.maven.wagon.providers.http.httpclient.client.
protocol.ResponseProcessCookies processCookies
WARNING: Cookie rejected: "[version: 0][name: rememberMe][value: deleteMe][domai
n: nexus.onebusaway.org][path: /nexus][expiry: Wed Apr 27 09:28:39 EDT 2016]". I
llegal path attribute "/nexus". Path of origin: "/content/groups/public/org/oneb
usaway/onebusaway-gtfs-modules/1.3.6/onebusaway-gtfs-modules-1.3.6.pom.sha1"
Downloaded: http://nexus.onebusaway.org/content/groups/public/org/onebusaway/one
busaway-gtfs-modules/1.3.6/onebusaway-gtfs-modules-1.3.6.pom (4 KB at 5.9 KB/sec
)
Downloading: http://nexus.onebusaway.org/content/groups/public/org/onebusaway/on
ebusaway-gtfs-modules/1.3.6/onebusaway-gtfs-modules-1.3.6.jar
Apr 27, 2016 9:28:39 AM org.apache.maven.wagon.providers.http.httpclient.client.
protocol.ResponseProcessCookies processCookies
WARNING: Cookie rejected: "[version: 0][name: rememberMe][value: deleteMe][domai
n: nexus.onebusaway.org][path: /nexus][expiry: Wed Apr 27 09:28:39 EDT 2016]". I
llegal path attribute "/nexus". Path of origin: "/content/groups/public/org/oneb
usaway/onebusaway-gtfs-modules/1.3.6/onebusaway-gtfs-modules-1.3.6.jar"
Downloading: http://repo.maven.apache.org/maven2/org/onebusaway/onebusaway-gtfs-
modules/1.3.6/onebusaway-gtfs-modules-1.3.6.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.636 s
[INFO] Finished at: 2016-04-27T09:28:39-04:00
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project onebusaway-client-library: Could not r
esolve dependencies for project org.onebusaway:onebusaway-client-library:jar:1.0
.0-SNAPSHOT: Could not find artifact org.onebusaway:onebusaway-gtfs-modules:jar:
1.3.6 in public.onebusaway.org (http://nexus.onebusaway.org/content/groups/publi
c/) -> [Help 1]
[ERROR]
~~~

**Comment by russellhoff** [comment]
@barbeau I did not, but what I did is make use of Jitpack (which does almost the same). I don't have any problem right now.

**Comment by sheldonabrown** [comment]
onebusaway-gtfs-modules is a pom not a jar.  You have an error in your maven dependency configuration.  What are you trying to import?  (And yes, 1.3.6 is there, I checked the repo)
